pd0 <- read.table("household_power_consumption.txt", header = TRUE, sep=";",na.strings="?")
pd0[['Date']] <- as.Date(strptime(pd0[['Date']], format='%d/%m/%Y'))
pd0sub <- subset(pd0, Date == "2007-02-01" | Date == "2007-02-02")
par(mfrow = c(1,1))
png("plot1.png", width = 480, height = 480)
hist(pd0sub$Global_active_power, col = "red", xlab = "Global Active Power(kilowatts)", ylab = "Frequency", main="Global Active Power")
dev.off()
